### ISSUE TITLE
playing skippable ads on iOS

### ISSUE THREAD

**Issue by tonykor** [googleads/videojs-ima#345]
Hello,
i'm getting

`Ad error: AdError 1005: The provided ad type: skippablevideo is not supported.`

on iOS Safari, and the main video is not playing. As far as know it doesn't currently support skippable ads, but why does it blocks player from watching the movie. 

`The media could not be loaded, either because the server or network failed or because the format is not supported`

And the play button always in loading state. I have a standard simple config. 

```
        player.ima(imaOptions);
        player.ima.requestAds();
        // Remove controls from the player on iPad to stop native controls from stealing
        // our click
        var contentPlayer =  player.el().getElementsByTagName('video')[0];
        if ((navigator.userAgent.match(/iPad/i) ||
              navigator.userAgent.match(/Android/i)) &&
            contentPlayer.hasAttribute('controls')) {
          contentPlayer.removeAttribute('controls');
        }
        // Initialize the ad container when the video player is clicked, but only the
        // first time it's clicked.
        var startEvent = 'click';
        if (navigator.userAgent.match(/iPhone/i) ||
            navigator.userAgent.match(/iPad/i) ||
            navigator.userAgent.match(/Android/i)) {
          startEvent = 'touchend';
        }
        player.one(startEvent, function() {
            player.ima.initializeAdDisplayContainer();
            player.play();
        })
```

Movies without ads (Empty VAST file) playing ok. 
BTW is there any updates on playing skippable ads on iOS, like on youtube.

Regards,
Tony

**Comment by shawnbuso** [comment]
Are you still seeing this issue? If I test in our advanced example with a sample skippable tag I see the content play.

**Comment by tonykor** [comment]
fixed all the problems with iPhones by not loading IMA on iPhones at all until it will not support skippable ads. As i'm currently have only skipable ads. As far as i know the problem disappeared, may be it was some cache issue or similar.

**Comment by denisvlr** [comment]
This doesn't seem to work, for example paste this sample tag in the advanced example:
```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator={timestamp}
```
Error:
```
Ad error: AdError 1005: The provided ad type: skippablevideo is not supported.
```

According to this thread this is still not supported by the main IMA SDK:
https://groups.google.com/forum/#!msg/ima-sdk/jYE6j4_YCko/m6HuIkM9uKMJ
