### ISSUE TITLE
Mid Roll not working on Mobile IOS

### ISSUE THREAD

**Issue by samueleastdev** [googleads/videojs-ima#482]
Hi,

I am updating our whole setup to video js 6 and after running some tests on my iPhone I noticed the midroll does not seem to work.

Process

1. Loads the pre-roll (no issues).
2. Gets to the mid-roll time and stops no ad plays, you have to click play and it will start again at that position.

I started to set up an example but then I noticed I am getting exactly the same issue here.

https://googleads.github.io/videojs-ima/examples/playlist/

Here is a video screengrab of the issue.

https://goo.gl/uhCNSg

Thanks

**Comment by shawnbuso** [comment]
Thanks for the detailed report - we'll take a look at this and should have it resolved soon.

**Comment by samueleastdev** [comment]
thanks @shawnbuso ;)

**Comment by shawnbuso** [comment]
Taking a look at this now - can you tell me what version of iOS you're on? The minor version is important too, e.g. iOS 11.1, not just iOS 11. Thanks!

**Comment by samueleastdev** [comment]
Hi @shawnbuso I am running on version 11.2.1

**Comment by shawnbuso** [comment]
Perfect, thanks!

**Comment by shawnbuso** [comment]
FYI this is an issue in the IMA SDK, not specific to this extension. It should be fixed with their next release, which the plugin will pick up automatically each time it's loaded on a page.

**Comment by samueleastdev** [comment]
Thanks for the update @shawnbuso how do I get notified when a new update to the IMA SDK has been submitted is there somewhere I can follow?

**Comment by shawnbuso** [comment]
We've got a [forum thread](https://groups.google.com/forum/#!topic/ima-sdk/tm1DMEMA758%5B1-25%5D) where we post updates. You can also keep an eye on the [release notes page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history).

**Comment by samueleastdev** [comment]
Awesome thanks @shawnbuso in the meantime I am going to put together a test suite in jsbin with various examples similar to the one they have on the video js hls contributor github read me http://jsbin.com/vokipos/8/edit?html with unpkg urls, I am also getting some strange results with hls.

**Comment by shawnbuso** [comment]
Thanks for the info - we do have a known issue with the video.js HLS plugin, see #314

**Comment by samueleastdev** [comment]
Ok thanks @shawnbuso for letting me know I have set up a basic test suite here in jsbin

http://output.jsbin.com/ponica/18

Might be helpful for testing I know you have samples in the docs but this may be helpful for live tests on the fly and being able to easily switch version etc.

**Comment by shawnbuso** [comment]
Great resource, thanks! We do also have the samples in the repo hosted at http://googleads.github.io/videojs-ima/

**Comment by jonigl** [comment]
Hi, I noticed that this problem is still happening but now is closed. The v1.0.4 resolves this issue?

**Comment by shawnbuso** [comment]
This was an issue in the IMA SDK, so it was fixed with [their release on 1/10](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history).

**Comment by jonigl** [comment]
@shawnbuso Sorry I was testing every day and this issue is still happening.

**Comment by shawnbuso** [comment]
My mistake - it looks like this issue is fixed in the IMA SDK at head, but the fix didn't make it into the 1/10 release. It will be in the next release. I'll double-check that this is resolved then.
