### ISSUE TITLE
integrate Google IMA ads at cuechange metadata event listener

### ISSUE THREAD

**Issue by sunilkumarjena21** [googleads/videojs-ima#536]
Hi @shawnbuso,

We wanted to integrate Google IMA ads at 'cuechange' metadata event listener. After Lot of try we are unable to get the ads played at the particular 'cuechange' event.

Any help will be highly apreciated. My implementation given  below in the link.Please copy the link in browser address if its won't work.

[https://codepen.io/sunilkumarjena21/pen/GQPvqg](url)

Thanks in advance

**Comment by shawnbuso** [comment]
Do you have a sample page I could take a look at? I checked out the codepen link you provided but it looks like that's just a snippet of your script and not the full implementation. Thanks!

**Comment by sunilkumarjena21** [comment]
Hi @shawnbuso,
Thanks for your swift response.
Here is the sample page.I have made some code comments as well to be better understanding. Please have a look.
[DemoCUEPOINT_IMA.zip](https://github.com/googleads/videojs-ima/files/1771505/DemoCUEPOINT_IMA.zip)

Please let me know,if anything else you want.

Thanks
Sunil

**Comment by shawnbuso** [comment]
Ah ok, I think the issue is that you're trying to interact with contrib-ads directly, and competing with IMA. For example, I see that your code is calling player.ads.startLinearAdMode(), but the IMA plugin is already calling that. It might make sense for you to try setting autoPlayAdBreaks to false, and then calling playAdBreak() when you reach an ad cue point.

**Comment by sunilkumarjena21** [comment]
Hi @shawnbuso,
Thanks for your swift response.
I have updated the implementation as per your suggestion.And now i am able to play the midroll ads in the cue point.So want to thanks for this.

Here in this implementation background content player paused the content until the mid-roll  completed.Please note this implementation is for live stream.I want suggestion from you,what should be the best approach to implement this.

1st approach:-Player seek bar can be seeked till the cue endTime.We do not have the code implementation for this right now.you can suggest code for this.

2nd approach:-We may not pause the content in the background content player rather play the live content in the background itself and muted its sound only.So that when all the ads playback completed,we only have to check do it as per the below code.
   
`player.on("timeupdate", function () {
                if (cues != null) {                  
                    if (player.currentTime() >= cues[0].endTime) {
                        player.ima.discardAdBreak();  // this is throwing error.
                        console.log('Ad cancelled');
                        cues = null;
                    }
                }
            })`

Please find the updated code.

[Demoplayer2.zip](https://github.com/googleads/videojs-ima/files/1776344/Demoplayer2.zip)

Thanks in advance!

**Comment by shawnbuso** [comment]
I think the second approach is probably best - that's what I've seen some live players do. For example, on Twitch if the streamer hits their ad button the stream keeps going in the background, just muted, so you're not behind when you get back after the ad.

**Comment by sunilkumarjena21** [comment]
Hi Shawn,

At the outset ,I would like thank you for you continues support & for your suggestion.

As suggested we try to implement the things but we are still facing some issues.We want suggestion on below two key points.

1st Point:-To providing a good experience for ads in live streams is to play the stream muted in the background while the ad plays in a container.For this we found the below stuff on some forum.

`shouldPlayContentBehindAd` check manages this: it returns true if the duration is Infinity (live stream).
Please let us know..the correct way to implement this, if its correct way to do through IMA SDK.Some code snippet with the correct position to call will do our job little easier.

2nd Point:-We want to to stop the IMA-ads dynamically,when the cueEndTime occurs.To do this job we implemented the below code snippet.

`player.on("timeupdate", function () {
 if (cues != null) {
 if (player.currentTime() >= cues[0].endTime) { 
player.ima.discardAdBreak(); // this is throwing error.
 console.log('Ad cancelled'); 
cues = null;
 } } 
})`
But the `player.ima.discardAdBreak();`  throwing ` ERROR: TypeError: player.ima.discardAdBreak is not a function`.

Please do suggest on the above two issues.

Thanks in advance!

**Comment by shawnbuso** [comment]
For your first point I think this will actually be difficult with the IMA plugin - it handles as much as it can for you, which means it is pausing and resuming content for you. You might be better off forking the repo adding checks for live streams in [contentPauseRequested](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L386) and [contentResumeRequested](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L397) that just mute and unmute the video instead of pausing and resuming it.

For your second point, the issue is that the `discardAdBreak` method is not exposed by the plugin, so you would need to add that. That's something you could do in your fork as well - you'll need to add it to ima-plugin.js, which will call `controller.discardAdBreak`, which will call `sdkImpl.discardAdBreak`. As an example, you can see how we've implemented initializeAdDisplayContainer - that has the same control flow from ima-plugin, through the controller, to sdk-impl.

**Comment by sunilkumarjena21** [comment]
Thanks Shawn! for your continuous support.

I think your suggestion is valid in the case when we completely do not want any preroll before the live content.But for our case we will integrate preroll as well along with Dynamic ad insertion at CuePoint.Thats why we do not want to permanently disable the contentPauseRequested feature because its best implementation for preroll & postroll.

So we integrated some custom code which works at the current moment.Please let us know if its correct way to do it.Becasue at the moment `event.type === google.ima.AdEvent.Type.ALL_ADS_COMPLETED` not firing for our code.So we implemented the below code.The demerits what we are thinking with this implementation is : we need to expliciting call `player.pause()` & `player.play();` each & every time when contentPauseRequested by the pluging. at `event.type === google.ima.AdEvent.Type.STARTED` & `event.type === google.ima.AdEvent.Type.COMPLETE`.Could you please let us now your opinion, if the player time syncing will be affected by this as we are explicitly playing & pausing the live streaming  when each ad started & ended.

attaching code implementation for your kind perusal.

[Demoplayer2.zip](https://github.com/googleads/videojs-ima/files/1782046/Demoplayer2.zip)


And do please let us know,why `event.type === google.ima.AdEvent.Type.ALL_ADS_COMPLETED` not firing for our code.

2nd query:Can we call `discardAdBreak()` directly from our code without changing IMA plugin.What is the correct way to call it.Becasue we call it by following way but its not working for our case.
`google.ima.adsManager.discardAdBreak()`.Please let us know how to call the Googles `stop()` function as well similar to`discardAdBreak()`

Thanks
Sunil

**Comment by shawnbuso** [comment]
STARTED and COMPLETE will fire for every ad, regardless of whether or not it is a pre-roll. What you probably want to do is set some kind of flag to track whether you have shown a pre-roll yet or not, and if you haven't shown a pre-roll, treat the current ad as a pre-roll.

ALL_ADS_COMPLETED will only fire when all pre-, mid-, and post-roll ads for an entire VMAP response have played - so you won't see it until then.

The only way you could call discardAdBreak from your plugin would be by getting a handle to the adsManager via an adsManagerLoadedCallback which you can pass as an option to the plugin. Take a look at [how we use that in the advanced example](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js#L72) - instead of just adding events like we do, you can call `player.ima.getAdsManager()` and store a local copy of that. However I must caution you against doing this because the plugin is *very much* designed to be self-contained, and this could break the internal state of the plugin. You'd be much better off forking the repo as I suggested and going that route.

**Comment by sunilkumarjena21** [comment]
Hi Shawn!

Thanks for your quick response.

Will try both the approach as you suggested above & let you know the result.

Could you please let us know why the below error appear after we made the `autoPlayAdBreaks :false,` in the `options`.And way to remove it.Actually the error points to videojs.ima.js:1395.

`videojs.ima.js:1395 Uncaught TypeError: this.adBreakReadyListener is not a function
    at SdkImpl.onAdBreakReady (videojs.ima.js:1395)`

Thanks
Sunil

**Comment by shawnbuso** [comment]
Are you calling `player.ima.setAdBreakReadyListener()` with a valid function? You'll see this error if not.

**Comment by sunilkumarjena21** [comment]
Hi Shawn!
Thanks for your quick support!
Could you please let us know..way to call it with a valid function?And proper place to call this please?

Thanks
Sunil

**Comment by shawnbuso** [comment]
You'll need to define a function and then pass it as a variable to that method. For example:

```
function myAdBreakReadyListener() {
  // Do stuff on ad break ready.
}

player.ima.setAdBreakReadyListener(myAdBreakReadyListener);
```

**Comment by sunilkumarjena21** [comment]
Thanks!

Calling it like below .Still i am seeing the same error.

`
        Ads.prototype.adsManagerLoadedCallback = function () {
            var events = [
                google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
                google.ima.AdEvent.Type.CLICK,
                google.ima.AdEvent.Type.COMPLETE,
                google.ima.AdEvent.Type.FIRST_QUARTILE,
                google.ima.AdEvent.Type.LOADED,
                google.ima.AdEvent.Type.MIDPOINT,
                google.ima.AdEvent.Type.PAUSED,
                google.ima.AdEvent.Type.RESUMED,
                google.ima.AdEvent.Type.STARTED,
                google.ima.AdEvent.Type.THIRD_QUARTILE
            ];

            for (var index = 0; index < events.length; index++) {
                player.ima.addEventListener(
                    events[index],
                    this.onAdEvent.bind(this));
            }

            adsManager=player.ima.getAdsManager();
            player.ima.setAdBreakReadyListener(myAdBreakReadyListener);
        };

        function myAdBreakReadyListener() {
            // Do stuff on ad break ready.
        }`

**Comment by shawnbuso** [comment]
Can you send a full, unobfucsated sample page so I can debug? Thanks.

**Comment by sunilkumarjena21** [comment]
Hi Shawn!

Updated unobfucsated code!Please find the sample page zip.
[Demoplayer2.zip](https://github.com/googleads/videojs-ima/files/1782346/Demoplayer2.zip)

Thanks
Sunil

**Comment by shawnbuso** [comment]
It looks like that's actually a bug in the plugin - it'll be fixed with https://github.com/googleads/videojs-ima/pull/551.

I tested against that patch and the error goes away, but I'm still seeing an error for an unsupported media file, so I think the hls-js part of your implementation will need some work.

**Comment by sunilkumarjena21** [comment]
Thanks Shawn for your continued support!
Looks like the bug has been fixed after the updated version.

Secondly ,I have fixed the HLS part.Now you can able to see the playable media files.
Could you please check the sound mute & unmute part of our implementation.And let us know if its correct way to do.Attached code for your kind perusal.

[Demoplayer2.zip](https://github.com/googleads/videojs-ima/files/1785725/Demoplayer2.zip)


Thanks
Sunil

**Comment by shawnbuso** [comment]
I'm still getting errors with that page, and if you've changed code in videojs.im.js I'm going to need that as well - the zip you have linked just contains DemoPlayer2.html

**Comment by sunilkumarjena21** [comment]
Hi Shawn,

I have changed the IP by domain name.Hope it will resolve the errors.I am attaching the Demoplayer which is included the changes of IMA-plugin through URL.You can check that as well downloading the URL from browser.

[Demoplayer2.zip](https://github.com/googleads/videojs-ima/files/1796912/Demoplayer2.zip)


Thanks
Sunil

**Comment by shawnbuso** [comment]
That's still erroring for me :/ It looks like ion.net.in is down, so all of your resources are failing to load.

**Comment by sunilkumarjena21** [comment]
Hi Shawan,

Sorry for long delay in getting back to you.I have now put all the resources in AWS.
You can check the below link & let us know,if its accessible to you now.

[http://13.127.181.162/video/Demoplayer2.html](url)

And one more point i wanted to highlight is,
is there any way in the SDK to call separate adtag URL to load separate video Ads.If yes, how can we show one banner Ad with progress bar in between two video Ads.
Note:-The progress bar with one banner Ad is needed to load the second video Ad.

Thanks in advance!
Sunil

**Comment by shawnbuso** [comment]
I'm seeing that page work as expected - are you still having problems or did you just want to confirm that it's working?

For your second question, currently I don't think we support what you're looking for. We support VMAP, which allows you to define a playlist of ads to be played at specific times in a stream, but nothing like what you're asking where an ad is dependent on a previous ad playing.

**Comment by sunilkumarjena21** [comment]
Hi Shawn!
Thanks for validating our solution 👍 

Regarding second case - Can we use `vjs.ima().setContentWithAdTag(null, midroll.tag, true);` for loading individual Video Ads?

Thanks
Sunil

**Comment by shawnbuso** [comment]
I'd definitely recommend going the VMAP route instead of scheduling the ad breaks yourself. If you're using  DFP as your ad server, you can check out the help center article [here](https://support.google.com/dfp_premium/answer/1406418?hl=en) for more info. If you're using a different ad server, I'd recommend looking at their documentation to see if they have their own info on VMAP. If you want to try to write your own VMAP, you can take a look at the responses from our sample VMAP tags [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags) and copy that format.

**Comment by sunilkumarjena21** [comment]
Hi Shawn,
Hope you're doing great.
Just wanted to get some help from your side regarding live content ad insertion support.
is there anything special, we need to do for Live video CUE_OUT & CUE_IN detection.& insert IMA.Or is it very much similar to the above implementation, what we have done for VOD content?

Secondly:-I have raised one feature request to Greg Smith regarding Live Streaming ad insertion support and got the notification that said the feature implemented.

contentIsLive option added in 6.3.0, documented here: http://videojs.github.io/videojs-contrib-ads/integrator/options.html
[https://github.com/videojs/videojs-contrib-ads/issues/344](url)

is this already incorporated in VideoJS-IMA?

Do we need to call some special function to implement live video IMA ad insertion ?

Thanks in advance!

Regards
Sunil
