### ISSUE TITLE
IMA SDK not working on Android chrome browser

### ISSUE THREAD

**Issue by eliasasmar** [googleads/videojs-ima#933]
Dears,
I have implemented the IMA SDK into my website and the ads are working perfectly on all devices (laptops, ios phones ...)
except on Android with Chrome version 84.0.4147.125 the ad didn't play.
I am  using the VideoJS IMA plugin.
You can find below a link where I have implemented the video.
https://www.specialarabia.com/en/details/Makeup-Tutorial-with-Fady-Kataya.

Please advise if anyone can help.
Thank you

**Comment by Kiro705** [comment]
Hello @eliasasmar ,

Sorry for the delayed reply. I was aware of an issue with Chrome v84 and IMA on Android, but I believe the issue was resolved.

However when checking your link, ads were not able to be played, and I received the following error:
`videojs.ima.js:1447 AdsLoader error: AdError 303: No Ads VAST response after one or more Wrappers`

Are you also seeing this 303 error currently? Also, are you still experiencing issues with Chrome on Android?

Thank you,
Jackson
IMA SDK DevRel

**Comment by eliasasmar** [comment]
Hi Jackson,

Thanks for your reply.
Yes I am still facing the same problem on mobile android. The ads are not playing on mobile. 
You can check below a new video we added on the website.
The Ad is working perfectly on laptop once we click the play button but on android nothing happens. 
https://www.specialarabia.com/en/details/L-Oreal-Paris-highlighting-the-Regions-most-inspiring-women

The error you mentioned is not showing but Once I open google chrome console in browser and click on play I am getting the below error 
Uncaught TypeError: Cannot read property 'innerHTML' of null
    at Ads.log (ads.js?v=1:110)
    at Ads.onAdEvent (ads.js?v=1:106)
    at Hh (ima3.js:112)
    at Y.l.dispatchEvent (ima3.js:110)
    at dy (ima3.js:471)
    at Y.Zd (ima3.js:468)
    at Hh (ima3.js:112)
    at Vv.l.dispatchEvent (ima3.js:110)
    at Vv.F (ima3.js:404)
    at Eh (ima3.js:107)
    at Bh (ima3.js:108)
    at b (ima3.js:105)

Please advise 
Thank you 
Elias Asmar

**Comment by Kiro705** [comment]
Hello @eliasasmar ,

Sorry for the delay in response. I was able to reproduce the issue using a Pixel 3 device and the web page provided. I was also able to reproduce the issue on the IMA's [video suite inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector?tag=https%253A%252F%252Fpubads.g.doubleclick.net%252Fgampad%252Fads%253Fiu%253D%25252F21894097782%25252FSpecialaarabia_instream%2526description_url%253Dhttps%25253A%25252F%25252Fwww.specialarabia.com%25252Fen%2526tfcd%253D0%2526npa%253D0%2526sz%253D288x216%25257C400x300%25257C480x360%25257C640x480%25257C1216x684%2526cust_params%253DSpecialArabia_Lang%25253DEnglish%2526gdfp_req%253D1%2526output%253Dxml_vast4%2526unviewed_position_start%253D1%2526env%253Dvp%2526correlator%253D2022750847875278%2526vpa%253Dclick%2526vpmute%253D0%2526sdkv%253Dh.3.409.0%2526osd%253D2%2526frm%253D0%2526vis%253D1%2526sdr%253D1%2526hl%253Den%2526ciu_szs%253D728x90%2526is_amp%253D0%2526u_so%253Dl%2526mpt%253Dvideojs-ima%2526mpv%253D1.8.1%2526adsid%253DChEI8Kn8-gUQ7srazo_Rk7GSARJMAESzQJ8Yt6w3i0fSmZsIA5t7x6HLsmLxly8zCk-zysEZd9O6BVaWgbwjnHjFILVFr-e4S5kMsTxU50m73-lxA_oAqxWoyZRjihlLsQ%2526jar%253D2020-09-14-14%2526sdki%253D44d%2526adk%253D770354334%2526sdk_apis%253D2%25252C8%2526media_url%253Dhttps%25253A%25252F%25252Fvideocdn.kwikmotion.com%25252Fspecialarabiavideos%25252FL%252525E2%25252580%25252599OREAL%25252520PARIS%252525E2%25252580%25252599%25252520%252525E2%25252580%25252598I%25252520AM%25252520INFALLIBLE%252525E2%25252580%25252599%25252520CAMPAIGN%25252520HIGHLIGHTING%25252520THE%25252520REGIONS%25252520MOST%25252520INSPIRING%25252520WOMEN.mp4%2526url%253Dhttps%25253A%25252F%25252Fwww.specialarabia.com%25252Fen%25252Fdetails%25252FL-Oreal-Paris-highlighting-the-Regions-most-inspiring-women%2526eid%253D44717394%2526dlt%253D1600095091884%2526idt%253D1171%2526dt%253D1600095105076%2526cookie%253DID%25253D252b70922ebc05e6%25253AT%25253D1600094996%25253AS%25253DALNI_MbhJZLyih8jQrURgXnL81S5buS3Mg%2526scor%253D1056591549423323%2526ged%253Dve4_td13_tt12_pd13_la0_er217.0.217.0_vi217.0.857.360_vp0_eb16491). This suggests to me that it is an issue with the IMA SDK itself and not the videojs-ima plugin. I will be raising an issue with the IMA team to resolve this bug.

As a note, this was not reproducible using the an Android emulator from desktop chrome.

Thank you,
Jackson
IMA SDK DevRel

**Comment by Kiro705** [comment]
Hello @eliasasmar ,

After talking with the IMA team, it looks like there will not be a change coming from the SDK to fix this issue. As a workaround I recommend setting adsRenderingSettings in the [additional settings section](https://github.com/googleads/videojs-ima#additional-settings) to avoid type 'application/x-mpegURL' type. Please see the below example on how to set the adsRenderingSettings object.

```
adsRenderingSettingsObject = {
    mimeTypes: [
        'video/mp4',
        'video/webm',
    ],
}
```

Let me know if you have any follow up questions,

Thank you,
Jackson
IMA SDK DevRel

**Comment by im841623** [comment]
Hello
I try to do this, but it is not work 

my code

var imaOptions = {
    id: 'content_video',
    adTagUrl: myAdTagUrl,
	adsRenderingSettings:{mimeTypes:['video/mp4']}
  };
